#!/usr/bin/osascript
-- make_alias: Create a Finder alias to a file

-- TODO Wrap this in a shell script to silence unnecessary output
-- TODO Clean up error messages

on run argv
    -- Check that two arguments were passed
    if (count of argv) = 2 then
        -- Check the first argument; expand it
        set target_path to item 1 of argv
        try
            set expanded_target_path to do shell script "echo " & quoted form of target_path & " | xargs realpath"
        on error errorMessage number errorNumber -- Most likely, the target file does not exist
            error errorMessage number 1
        end try
        set test_file to POSIX file expanded_target_path
        tell application "Finder"
            if exists test_file then
                set is_alias to (class of item test_file is alias file)
            else
                set is_alias to false
            end if
            if is_alias then
                error "Cannot create an alias to an alias" number 1
            end if
        end tell

        set dest_path to item 2 of argv
        set dest_folder_name to do shell script "dirname " & quoted form of dest_path
        set dest_file_name to do shell script "basename " & quoted form of dest_path
        try
            set expanded_dest_folder_name to do shell script "echo " & quoted form of dest_folder_name & " | xargs realpath"
        on error errorMessage number errorNumber -- Most likely, the dest folder does not exist
            error errorMessage number 1
        end try
        set expanded_dest_path to expanded_dest_folder_name & "/" & dest_file_name
        
        tell application "Finder"
          set targetFile to POSIX file expanded_target_path as alias
          set destFolder to POSIX file expanded_dest_folder_name as alias
          
          make new alias file to targetFile at destFolder with properties {name:dest_file_name}
        end tell        
        return "Created alias"
    else
        error "Usage: make_alias <target> <alias_name>" number 1
    end if
end run
